const A="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const ROTORS={I:{w:"EKMFLGDQVZNTOWYHXUSPAIBRCJ",n:"Q"},II:{w:"AJDKSIRUXBLHWTMCQGZNPYFVOE",n:"E"},III:{w:"BDFHJLCPRTXVZNYEIWGAKMUSQO",n:"V"},IV:{w:"ESOVPZJAYQUIRHXLNFTGKDCMWB",n:"J"},V:{w:"VZBRGITYUPSDNHLXAWMJQOFECK",n:"Z"}};
const REFS={B:"YRUHQSLDPXNGOKMIEBFZCWVJAT",A:"EJMZALYXVBWFCRQUONTSPIKHGD"};
let cfg={rotors:["I","II","III"],ref:"B",pos:[0,0,0],plug:""},m,h=[],step={active:false,text:"",i:0,out:""};
function setup(){let c=createCanvas(1100,290);c.parent("canvas");["I","II","III","IV","V"].forEach(x=>{select("#r1").option(x);select("#r2").option(x);select("#r3").option(x)});["A","B"].forEach(x=>select("#ref").option(x));select("#r1").value("I");select("#r2").value("II");select("#r3").value("III");select("#ref").value("B");bind();reset();}
function bind(){select("#apply").mousePressed(apply);select("#default").mousePressed(defaults);select("#encode").mousePressed(encode);select("#start").mousePressed(start);select("#next").mousePressed(next);select("#finish").mousePressed(finish);select("#clear").mousePressed(clearAll)}
function apply(){let p=select("#pos").value().toUpperCase().replace(/[^A-Z]/g,"");let pb=select("#plug").value().toUpperCase().replace(/[^A-Z]/g,"");if(p.length!==3)return msg("A posição deve ter 3 letras.");if(pb.length%2||pb.length>8)return msg("Plugboard: 0 a 8 letras, sempre em pares.");if(new Set(pb).size!==pb.length)return msg("Uma letra não pode aparecer em dois pares.");cfg={rotors:[select("#r1").value(),select("#r2").value(),select("#r3").value()],ref:select("#ref").value(),pos:[...p].map(x=>A.indexOf(x)),plug:pb};reset();msg("Configuração aplicada.")}
function defaults(){select("#r1").value("I");select("#r2").value("II");select("#r3").value("III");select("#ref").value("B");select("#pos").value("AAA");select("#plug").value("");cfg={rotors:["I","II","III"],ref:"B",pos:[0,0,0],plug:""};reset();msg("Padrão restaurado.")}
function reset(){m=new Enigma(cfg);h=[];step={active:false,text:"",i:0,out:""};ui();}
function msg(x){select("#msg").html(x)}
function clean(){return select("#text").value().toUpperCase().replace(/[^A-Z]/g,"").slice(0,80)}
function encode(){let t=clean();if(!t)return msg("Digite uma mensagem.");m=new Enigma(cfg);h=[];let o="";for(let c of t){let r=m.enc(c);o+=r.o;h.push(r)}select("#in").html(t);select("#out").html(o);step={active:false,text:t,i:t.length,out:o};ui();}
function start(){let t=clean();if(!t)return msg("Digite uma mensagem.");m=new Enigma(cfg);h=[];step={active:true,text:t,i:0,out:""};select("#in").html(t);select("#out").html("—");ui();msg("Simulação iniciada.")}
function next(){if(!step.active)start();if(!step.active||step.i>=step.text.length)return;let r=m.enc(step.text[step.i++]);step.out+=r.o;h.push(r);select("#out").html(step.out);ui(r)}
function finish(){if(!step.active)start();if(!step.active)return;while(step.i<step.text.length){let r=m.enc(step.text[step.i++]);step.out+=r.o;h.push(r)}select("#out").html(step.out);ui();msg("Simulação concluída.")}
function clearAll(){select("#text").value("");select("#in").html("—");select("#out").html("—");reset()}
function plug(c,p){for(let i=0;i<p.length;i+=2){if(c===p[i])return p[i+1];if(c===p[i+1])return p[i]}return c}
class Enigma{constructor(c){this.r=c.rotors.map(x=>ROTORS[x]);this.names=c.rotors;this.ref=REFS[c.ref];this.p=[...c.pos];this.pb=c.plug}pos(){return this.p.map(x=>A[x]).join("")}step(){let b=this.pos();this.p[0]=(this.p[0]+1)%26;if(A[this.p[0]]===this.r[0].n)this.p[1]=(this.p[1]+1)%26;if(A[this.p[1]]===this.r[1].n)this.p[2]=(this.p[2]+1)%26;return[b,this.pos()]}f(i,k){let p=this.p[k],w=this.r[k].w;let q=(i+p)%26,o=(A.indexOf(w[q])-p+26)%26;return[o,A[o]]}rev(i,k){let p=this.p[k],w=this.r[k].w;let q=(i+p)%26,o=(w.indexOf(A[q])-p+26)%26;return[o,A[o]]}enc(c){let before=this.pos(),s=this.step(),x=plug(c,this.pb),i=A.indexOf(x);let a=this.f(i,2),b=this.f(a[0],1),d=this.f(b[0],0),rr=A.indexOf(this.ref[d[0]]),e=this.rev(rr,0),f=this.rev(e[0],1),g=this.rev(f[0],2),o=plug(g[1],this.pb);return{i:c,before,after:s[1],pin:x,r3:a[1],r2:b[1],r1:d[1],ref:A[rr],back1:e[1],back2:f[1],back3:g[1],o}}
}
function ui(last){select("#history").html(h.map((r,i)=>`<tr><td>${i+1}</td><td>${r.i}</td><td>${r.before}</td><td>${r.after}</td><td>${r.pin}</td><td>${r.r3} → ${r.r2} → ${r.r1}</td><td>${r.ref}</td><td>${r.back1} → ${r.back2} → ${r.back3}</td><td><b>${r.o}</b></td></tr>`).join(""));if(last){let v=[["Entrada",last.i],["Posição",last.after],["Plugboard",last.pin],["Rotor 3",last.r3],["Rotor 2",last.r2],["Rotor 1",last.r1],["Refletor",last.ref],["Rotor 1",last.back1],["Rotor 2",last.back2],["Rotor 3",last.back3],["Saída",last.o]];select("#path").html(v.map(x=>`<div class="pitem"><div class="plabel">${x[0]}</div><div class="pletter">${x[1]}</div></div>`).join(""));}else select("#path").html("Processe uma letra para visualizar o percurso.");redraw()}
function draw(){background(248);push();translate(15,10);fill(35);noStroke();rect(0,0,1070,270,18);fill(240);textAlign(CENTER,CENTER);textStyle(BOLD);textSize(21);text("MÁQUINA ENIGMA",535,25);for(let i=0;i<3;i++)rotor(170+i*260,115,"Rotor "+(i+1),cfg.rotors[i],m.p[i]);fill(245);ellipse(920,115,160,110);fill(30);textSize(28);text(cfg.ref,920,108);fill(210);textSize(12);textStyle(NORMAL);text("REFLETOR",920,154);fill(220);textSize(14);text("POSIÇÃO ATUAL: "+m.pos(),535,220);text("PLUGBOARD: "+(cfg.plug||"sem conexões"),535,245);pop()}
function rotor(x,y,t,n,p){fill(220);textSize(13);textStyle(BOLD);text(t,x,y-65);fill(245);stroke(80);strokeWeight(3);circle(x,y,115);noStroke();fill(30);textSize(28);text(n,x,y-8);textSize(20);text(A[p],x,y+28);fill(100);textSize(11);text("notch "+ROTORS[n].n,x,y+51)}
