name: Publish Quarto Book

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Cache Quarto
        uses: actions/cache@v4
        with:
          path: ~/.quarto
          key: ${{ runner.os }}-quarto

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y librsvg2-bin

      # Renderiza o livro somente em HTML
      - name: Render HTML
        run: |
          quarto render --to html

      # Configura o GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Envia o conteúdo de _book para o GitHub Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _book

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4